micronaut:
  application:
    name: nossaCasaDoCodigo

#datasouces:
#  default:
#    url: ${DB_URL:'jdbc:postgresql://localhost:3306/casa_do_codigo_micronaut'}
#    driverClassName: org.postgres.Driver
#    username: ${DB_USER:root}
#    password: ${DB_USER:root}
#
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

datasources:
  default:
    url: jdbc:mysql://localhost:3306/casa_do_codigo_micronaut
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_USER:root}

#datasources:
#  default:
#    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#    schema-generate: CREATE_DROP
#    dialect: H2
#jpa.default.properties.hibernate.hbm2ddl.auto: update
